"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var comissao_1 = require("./modules/comissao");
var covid_1 = require("./modules/covid");
var estatistivaCovid = new covid_1.DadosCovid(50, 55);
var estatistivaCovid2 = new covid_1.DadosCovid(50, 51);
var estatistivaCovid3 = new covid_1.DadosCovid(50, 70);
console.log(estatistivaCovid.calcularVariacao());
console.log(estatistivaCovid.getClassificacao());
console.log('\n');
console.log(estatistivaCovid2.calcularVariacao());
console.log(estatistivaCovid2.getClassificacao());
console.log('\n');
console.log(estatistivaCovid3.calcularVariacao());
console.log(estatistivaCovid3.getClassificacao());
var comissao = new comissao_1.Comissao('Lucas', 14000);
var comissao2 = new comissao_1.Comissao('Joao', 6000);
var comissao3 = new comissao_1.Comissao('Maria', 20000);
var comissao4 = new comissao_1.Comissao('Pedro', 40000);
console.log(comissao.calculaComissao());
console.log(comissao.salarioTotal());
console.log('\n');
console.log(comissao2.calculaComissao());
console.log(comissao2.salarioTotal());
console.log('\n');
console.log(comissao3.calculaComissao());
console.log(comissao3.salarioTotal());
console.log('\n');
console.log(comissao4.calculaComissao());
console.log(comissao4.salarioTotal());
//# sourceMappingURL=app.js.map